//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stanford_LamViecVoiEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stanfArticle
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ArticleContent { get; set; }
        public string Keyword { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdate { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
        public Nullable<bool> Published { get; set; }
        public string Notes { get; set; }
        public string AuthorName { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual stanfCategory stanfCategory { get; set; }
        public virtual stanfType stanfType { get; set; }
        public virtual stanfUser stanfUser { get; set; }
    }
}
